baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Aafu theme"
    author = "Aleks Novikov"
    description = "my academic website"
    copyright = "aleks novikov"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Aleks Novikov"
		tagline = "PhD candidate"
		location = "Tucson, AZ"
        photo = "site.jpeg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "#"
            title = "LinkedIn"		
        [[params.social.list]]
            class = "fab"
            icon = "fa-stack-overflow"
            url = "#"
            title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "#"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "#"
            title = "Twitter"
		[[params.social.list]]
            class = "ai"
            icon = "ai-google-scholar"
            url = "#"
            title = "Google Scholar"
		[[params.social.list]]
            class = "ai"
            icon = "ai-researchgate"
            url = "#"
            title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "I'm a PhD candidate in Second Language Acquisition."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Graduate Research Assistant"
            dates = "2019 - *Present*"
            company = "Corpus & Repository of Writing (Crow), University of Arizona"
            details = "Led Corpus Development Team. Helped recruit participants. Worked with scripts in Python & R. Drank water from office cooler. Ate donuts on people's birthdays."
        [[params.experience.list]]
            position = "Graduate Teaching Assistant"
            dates = "2013 - 2019"
            
            company = "Russian & Slavic Studies Department, University of Arizona"
            details = "Taught Russian as a Foreign Language: RSSS101, RSSS102, RSSS201, RSSS202"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "M.A. in Russian & Slavic Studies"
            college = "University of Arizona"
            dates = "2013 - 2015"
            thesis_title = "Pedagogical Perspectives on Russian Verbal Aspect: Corpus Study"
            thesis_link = "https://repository.arizona.edu/handle/10150/595952"
        [[params.education.list]]
            degree = "Specialist’s Degree in Translation & Interpretation"
            college = "Perm State Technical University, Perm, Russia"
            dates = "2006 - 2011"
            

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Book Chapters"]

        [[params.publication.list]]
            title = "Taking flight with MACAWS: Learner corpora building for less commonly taught languages"
            authors = "Novikov, A., Sommer-Farias, B., Picoral, A., Bertho, M., & Staples, S"
            date = "In Progress"
            journal = "International Journal of Corpus Linguistics"
        
            type = "Journal Articles"
       
		
        [[params.publication.list]]
            title = "Using a learner corpus as a medium between unfocused and focused awareness-raising tasks"
            authors = "Novikov, A., & Vinokurova, V"
            date = "Accepted"
            journal = "In S. Nuss & M. Whitehead-Martelle (Eds.). Russian through Task: Task-Based/Task Supported Instruction of RFL"
          
            type = "Book Chapters"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"            

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Skill 1, Skill 2"
            skillrating = 90
        [[params.skill.list]]
            skill = "Skill 3"
            skillrating = 80
        [[params.skill.list]]
            skill = "Skill 4"
            skillrating = 50

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Cooking"
        [[params.hobby.list]]		
		    hobby = "Hiking"
        [[params.hobby.list]]		
		    hobby = "Baking"
		    [[params.hobby.list]]		
		    hobby = "Backpacking"
